# Generated by Django 4.2.3 on 2026-05-16 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_entry', models.TextField()),
                ('mood', models.CharField(choices=[('Very Happy', 'Very Happy'), ('Happy', 'Happy'), ('Neutral', 'Neutral'), ('Sad', 'Sad'), ('Very Sad', 'Very Sad')], max_length=20)),
                ('stress_level', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Very High', 'Very High')], max_length=20)),
                ('anxiety_score', models.FloatField(default=0)),
                ('motivation_score', models.FloatField(default=0)),
                ('energy_level', models.IntegerField(default=5, help_text='1-10 scale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MotivationalTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('trigger_emotion', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductivitySuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mood_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivity_suggestions', to='emotion.moodentry')),
            ],
        ),
        migrations.CreateModel(
            name='MoodTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_average_mood', models.FloatField(default=0)),
                ('weekly_average_stress', models.FloatField(default=0)),
                ('weekly_average_anxiety', models.FloatField(default=0)),
                ('weekly_average_motivation', models.FloatField(default=0)),
                ('trend_direction', models.CharField(default='stable', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mood_trend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmotionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_emotions', models.JSONField(default=list)),
                ('sentiment_score', models.FloatField(default=0)),
                ('dominant_emotion', models.CharField(blank=True, max_length=100)),
                ('keywords', models.JSONField(default=list)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('mood_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='emotion.moodentry')),
            ],
        ),
    ]
