# Generated by Django 4.2.3 on 2026-05-16 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(default=list)),
                ('trending_skills', models.JSONField(default=list)),
                ('salary_range', models.CharField(max_length=100)),
                ('job_outlook', models.CharField(max_length=100)),
                ('average_experience_years', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_careers', models.JSONField(default=list)),
                ('recommended_skills', models.JSONField(default=list)),
                ('confidence_score', models.FloatField(default=0)),
                ('reasoning', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('Course', 'Course'), ('Tutorial', 'Tutorial'), ('Book', 'Book'), ('Project', 'Project')], max_length=50)),
                ('url', models.URLField()),
                ('difficulty_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('duration_hours', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_resources', to='career.careerpath')),
            ],
        ),
        migrations.CreateModel(
            name='CareerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_career', models.CharField(blank=True, choices=[('Software Engineer', 'Software Engineer'), ('Data Analyst', 'Data Analyst'), ('AI/ML Engineer', 'AI/ML Engineer'), ('UI/UX Designer', 'UI/UX Designer'), ('Product Manager', 'Product Manager'), ('DevOps Engineer', 'DevOps Engineer'), ('Full Stack Developer', 'Full Stack Developer'), ('Backend Developer', 'Backend Developer'), ('Frontend Developer', 'Frontend Developer'), ('Mobile Developer', 'Mobile Developer')], max_length=100)),
                ('secondary_careers', models.JSONField(default=list)),
                ('interests', models.JSONField(default=list)),
                ('career_readiness_score', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
